# Generated by Django 5.0.4 on 2024-05-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction', models.CharField(blank=True, max_length=50, null=True)),
                ('Sender_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Senders_country', models.CharField(blank=True, max_length=50, null=True)),
                ('Recipents_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Recipents_country', models.CharField(blank=True, max_length=20, null=True)),
                ('Senders_bank', models.CharField(blank=True, max_length=20, null=True)),
                ('Recipents_bank', models.CharField(blank=True, max_length=20, null=True)),
                ('Transfer_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('Transfer_date', models.DateTimeField(blank=True, max_length=20, null=True)),
                ('Status_update', models.CharField(blank=True, max_length=20, null=True)),
                ('Estimated_delivery', models.CharField(blank=True, max_length=20, null=True)),
                ('Recipents_IBAN', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
